// DO NOT EDIT this file.

package user

import (
	"context"
	"fmt"

	"google.golang.org/appengine/datastore"
	"google.golang.org/appengine/log"

	"github.com/akm/goa_model_gen/project1/model"
	goon "github.com/akm/goa_model_gen/project1/stores/goon_store"
)

type UserStore struct {
}

func (s *UserStore) All(ctx context.Context) ([]*model.User, error) {
	return s.Select(ctx, s.Query(ctx))
}

func (s *UserStore) Select(ctx context.Context, q *datastore.Query) ([]*model.User, error) {
	g := goon.FromContext(ctx)
	r := []*model.User{}
	log.Infof(ctx, "q is %v\n", q)
	_, err := g.GetAll(q.EventualConsistency(), &r)
	if err != nil {
		log.Errorf(ctx, "Failed to Select model.User because of %v\n", err)
		return nil, err
	}
	return r, nil
}

func (s *UserStore) CountBy(ctx context.Context, q *datastore.Query) (int, error) {
	g := goon.FromContext(ctx)
	c, err := g.Count(q)
	if err != nil {
		log.Errorf(ctx, "Failed to count model.User with %v because of %v\n", q, err)
		return 0, err
	}
	return c, nil
}

func (s *UserStore) Query(ctx context.Context) *datastore.Query {
	g := goon.FromContext(ctx)
	k := g.Kind(new(model.User))
	// log.Infof(ctx, "Kind for model.User is %v\n", k)
	return datastore.NewQuery(k)
}

func (s *UserStore) ByID(ctx context.Context, iD string) (*model.User, error) {
	r := model.User{ID: iD}
	err := s.Get(ctx, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

func (s *UserStore) ByKey(ctx context.Context, key *datastore.Key) (*model.User, error) {
	if err := s.IsValidKey(ctx, key); err != nil {
		log.Errorf(ctx, "UserStore.ByKey got Invalid key: %v because of %v\n", key, err)
		return nil, err
	}

	r := model.User{ID: key.StringID()}
	err := s.Get(ctx, &r)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

func (s *UserStore) Get(ctx context.Context, m *model.User) error {
	g := goon.FromContext(ctx)
	err := g.Get(m)
	if err != nil {
		log.Errorf(ctx, "Failed to Get model.User because of %v\n", err)
		return err
	}

	return nil
}

func (s *UserStore) IsValidKey(ctx context.Context, key *datastore.Key) error {
	if key == nil {
		return fmt.Errorf("key is nil")
	}
	g := goon.FromContext(ctx)
	expected := g.Kind(&model.User{})
	if key.Kind() != expected {
		return fmt.Errorf("key kind must be %s but was %s", expected, key.Kind())
	}
	return nil
}

func (s *UserStore) Exist(ctx context.Context, m *model.User) (bool, error) {
	if m.ID == "" {
		return false, nil
	}
	g := goon.FromContext(ctx)
	key, err := g.KeyError(m)
	if err != nil {
		log.Errorf(ctx, "Failed to Get Key of %v because of %v\n", m, err)
		return false, err
	}
	_, err = s.ByKey(ctx, key)
	if err == datastore.ErrNoSuchEntity {
		return false, nil
	} else if err != nil {
		log.Errorf(ctx, "Failed to get existance of %v because of %v\n", m, err)
		return false, err
	} else {
		return true, nil
	}
}

func (s *UserStore) Create(ctx context.Context, m *model.User) (*datastore.Key, error) {
	if err := m.PrepareToCreate(); err != nil {
		return nil, err
	}
	return s.PutWith(ctx, m, func() error {
		exist, err := s.Exist(ctx, m)
		if err != nil {
			return err
		}
		if exist {
			log.Errorf(ctx, "Failed to create %v because of another entity has same key\n", m)
			return fmt.Errorf("Duplicate ID error: %q of %v\n", m.ID, m)
		}
		return nil
	})
}

func (s *UserStore) Update(ctx context.Context, m *model.User) (*datastore.Key, error) {
	if err := m.PrepareToUpdate(); err != nil {
		return nil, err
	}
	return s.PutWith(ctx, m, func() error {
		exist, err := s.Exist(ctx, m)
		if err != nil {
			return err
		}
		if !exist {
			log.Errorf(ctx, "Failed to update %v because it doesn't exist\n", m)
			return fmt.Errorf("No data to update %q of %v\n", m.ID, m)
		}
		return nil
	})
}

func (s *UserStore) PutWith(ctx context.Context, m *model.User, f func() error) (*datastore.Key, error) {
	if err := s.Validate(ctx, m); err != nil {
		return nil, err
	}
	if f != nil {
		if err := f(); err != nil {
			return nil, err
		}
	}

	return s.Put(ctx, m)
}

func (s *UserStore) Put(ctx context.Context, m *model.User) (*datastore.Key, error) {
	g := goon.FromContext(ctx)
	key, err := g.Put(m)
	if err != nil {
		log.Errorf(ctx, "Failed to Put %v because of %v\n", m, err)
		return nil, err
	}
	return key, nil
}

func (s *UserStore) Delete(ctx context.Context, m *model.User) error {
	g := goon.FromContext(ctx)
	key, err := g.KeyError(m)
	if err != nil {
		log.Errorf(ctx, "Failed to Get key of %v because of %v\n", m, err)
		return err
	}
	if err := g.Delete(key); err != nil {
		log.Errorf(ctx, "Failed to Delete %v because of %v\n", m, err)
		return err
	}
	return nil
}

func (s *UserStore) ValidateUniqueness(ctx context.Context, m *model.User) error {
	conditions := map[string]interface{}{
		"Email": m.Email,
	}
	for field, value := range conditions {
		q := s.Query(ctx).Filter(field+" =", value)
		c, err := s.CountBy(ctx, q)
		if err != nil {
			return err
		}
		b := 0
		if m.IsPersisted() {
			b = 1
		}
		if c > b {
			return &model.ValidationError{
				Field:   field,
				Message: fmt.Sprintf("%v has already been taken", value),
			}
		}
	}
	return nil
}
